### ISSUE TITLE
Specifying apiDoc folder instead of api_data.json

### ISSUE THREAD

**Issue by krodnar** [fluix/web-apidoc2ts#70]
#### Nature of issue?

- [x] Existing feature enhancement
- [ ] New feature request

#### Issue description
To generate code you need to specify an exact path to the `api_data.json` which is not very convenient.

#### Solution
Instead of specifying the exact path users should be able to specify the path to the apiDoc folder and the tool should find `api_data.json` automatically.
This is also gonna be useful if in the future we will require any additional files from apiDoc.

**Comment by Krakabek** [comment]
Will do
